
---
apiVersion: install.tetrate.io/v1alpha1
kind: ControlPlane
metadata:
  name: controlplane
  namespace: istio-system
spec:
  tier1Cluster: true
  hub: xxx
  telemetryStore:
    elastic:
      host: xxx
      port: 443
  managementPlane:
    host: xxx
    port: 443
    clusterName: mgmt-cluster
    tenant: tetrate